# Architecture adapted from "Improving Unsupervised Defect
# Segmentation by Applying Structural Similarity to Autoencoders"
# https://arxiv.org/pdf/1807.02011

[network]
name = "MVTec AD Autoencoder"
type = "Autoencoder"
dataset = "MVTec AD"
mirrored = true
input_length = 256  # width implicitly defined; square image

[[network.encoder]]
# Conv1 Output: 16x128x128
# in_channels defined by grayscale or rgb input
name = "conv-1"
args.out_channels = 16
args.kernel_size = 4
args.stride = 2
args.padding = 1

[[network.encoder]]
# Conv2, Output: 32x64x64
name = "conv-2"
args.in_channels = 16
args.out_channels = 32
args.kernel_size = 4
args.stride = 2
args.padding = 1

[[network.encoder]]
# Conv3, Output: 32x32x32
name = "conv-3"
args.in_channels = 32
args.out_channels = 32
args.kernel_size = 4
args.stride = 2
args.padding = 1

[[network.encoder]]
# Conv4, Output: 32x32x32
name = "conv-4"
args.in_channels = 32
args.out_channels = 32
args.kernel_size = 3
args.stride = 1
args.padding = 1

[[network.encoder]]
# Conv5, Output: 64x16x16
name = "conv-5"
args.in_channels = 32
args.out_channels = 64
args.kernel_size = 4
args.stride = 2
args.padding = 1

[[network.encoder]]
# Conv6, Output: 64x16x16
name = "conv-6"
args.in_channels = 64
args.out_channels = 64
args.kernel_size = 3
args.stride = 1
args.padding = 1

[[network.encoder]]
# Conv7, Output: 128x8x8
name = "conv-7"
args.in_channels = 64
args.out_channels = 128
args.kernel_size = 4
args.stride = 2
args.padding = 1

[[network.encoder]]
# Output: 64x8x8
name = "conv-8"
args.in_channels = 128
args.out_channels = 64
args.kernel_size = 3
args.stride = 1
args.padding = 1

[[network.encoder]]
# Output: 32x8x8
name = "conv-9"
args.in_channels = 64
args.out_channels = 32
args.kernel_size = 3
args.stride = 1
args.padding = 1

[[network.encoder]]
# Output: 100x1x1, latent space
name = "conv-10"
args.in_channels = 32
args.out_channels = 100
args.kernel_size = 8
args.stride = 1
args.padding = 0
