name = "CIFAR10_LeNet"

[[network]]

[[network.conv1]]
conv.in_channels  = 3
conv.out_channels = 32
conv.kernel_size  = 5
conv.padding      = 2

[[network.conv1]]
bn.in_channels    = 3
bn.eps		  = 1e-4


[[network]]
[[network.conv2]]
conv.in_channels = 8

[[network.conv2]]
bn.in_channels = 4


